name: CI/CD for Spring Boot Java Application

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          maven-version: '3.8.4'

      - name: Set new version with Maven
        run: mvn versions:set -DnewVersion=0.${{ github.run_number }}.0

      - name: Build the Spring Boot application
        run: mvn clean install

      - name: Build Docker image
        run: |
          docker build -t asadullahkhan/java-21-gsm-app:tagname:0.${{ github.run_number }}.0 -f Dockerfile .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push asadullahkhan/java-21-gsm-app:tagname:0.${{ github.run_number }}.0

      # - name: Update Helm chart with new image tag
      #   run: |
      #     helm repo update
      #     helm upgrade my-spring-boot-app ./helm-chart --set image.tag=${{ github.run_number }} --namespace my-namespace --reuse-values

      # - name: Sync with ArgoCD (optional)
      #   run: |
      #     argocd app sync my-spring-boot-app --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }}
