name: CI/CD for Spring Boot Java Application

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          # maven-version: '3.8.4'


      - name: Set new version with Maven
        run: mvn versions:set -DnewVersion=0.${{ github.run_number }}.0

      - name: Build the Spring Boot application
        run: mvn clean install

      - name: Build Docker image
        run: |
          docker build -t asadullahkhan/java-21-gsm-app:0.${{ github.run_number }}.0 -f Dockerfile .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push asadullahkhan/java-21-gsm-app:0.${{ github.run_number }}.0

      - name: Checkout Helm chart repository
        uses: actions/checkout@v3
        with:
          repository: 'AsadUkh/secure-java21-gsm-api-helm'
          token: ${{ secrets.PAT_FOR_HELM }}
          path: helm-chart-repo

      - name: Update imageTag in values.yaml
        run: |
          sed -i 's/^imageTag:.*/imageTag: "${{ github.run_number }}"/' helm-chart-repo/values.yaml
          cd helm-chart-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add values.yaml
          git commit -m "Update imageTag to ${{ github.run_number }}"
          git push origin master
